name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: |
          cd acai-app
          npm install

      - name: Build
        run: |
          cd acai-app
          npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # The branch the action should deploy to.
          folder: acai-app/build     # The folder the action should deploy.
          token: ${{ secrets.GITHUB_TOKEN }}  # Usa o GITHUB_TOKEN para autenticação
        
    
    
